### ISSUE TITLE
length limits for channel part of fdsn source identifier

### ISSUE THREAD

**Issue by crotwell** [iris-edu/xseed-specification#18]
The 20190506 draft has length limits of 8 chars for network, station and location codes, but no mention of limits for the channel code part. Is it 8 as well or unlimited? Presumably due to the length byte in xseed header, it is limited to 255 total.

**Comment by chad-iris** [comment]
In the soon-to-be-proposed XFDSN: identifiers there is no limit.  Furthermore, the "channel" has been logically separated into three different components that, for the moment, have fixed values.

To put it simply, we do not need a limit for a "channel" because it is already limited by the allowed codes.

**Comment by crotwell** [comment]
So if channels are still limited to 3 chars, why do we have separators? I thought the whole point of making the channel code part be B_H_Z was to allow multiple characters?

Seems like, especially with the explosion of SOH channels, expanding the chan code is as important as expanding the station and loc codes.

**Comment by chad-iris** [comment]
> So if channels are still limited to 3 chars, why do we have separators? I thought the whole point of making the channel code part be B_H_Z was to allow multiple characters?

The separators are to _allow_ for multi-character codes, that are yet-to-be-defined.  The FDSN could well define more codes before the scheme is adopted.

**Comment by crotwell** [comment]
By that argument, why put limits on the network, station and location in the spec? Aren't those just as much FDSN decisions as the channel code part?

I'm ok with either no length limits in the urn spec, or specifying limits for all parts. But some and not others feels weird.

**Comment by chad-iris** [comment]
> I'm ok with either no length limits in the urn spec, or specifying limits for all parts. But some and not others feels weird.

All the limits are in the spec, either stated explicitly (in the case of network, station, location) or implicitly by what is defined as allowed content (in the case of band, source, position).  In the later case, stating a limit would be redundant and put the FDSN in a position where a future decision to expand one of the codes breaks an independent limit rule.

A gray area would be where "administrative" channels allow creates to "make up" some of the codes, there should be guidance on that.
