### ISSUE TITLE
less zeros in reference data

### ISSUE THREAD

**Issue by crotwell** [iris-edu/xseed-specification#25]
Might be better for testing if there were less zeros in the reference data. Particularly, the hour, min, sec and nanosec are all zeros, making unit tests less reliable. Perhaps, time could be something like:  12:34:56.123456789.

Related, would be good if the sample rate/period was not always 1. Because the "negative means period" concept, a reference files with high sample rate (>> 1) and low sample rate (<< -1) would be really useful to catch parse errors.

**Comment by crotwell** [comment]
Did you mean move the issue, the actual reference data, or both?

Reference data is not in the miniSEED3 repo as far as I can tell.

**Comment by chad-iris** [comment]
They were in master, but not draft, branch (wrong way around, shame on me).  I've synched them and now they're present in all/both branches.

**Comment by chad-iris** [comment]
Add: so the issue should be moved, this repo is no longer relevant.

**Comment by chad-iris** [comment]
Re-issued:
https://github.com/iris-edu/miniSEED3/issues/1
